import os
import re
import json
import uuid
import shutil
from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

from groq import Groq
from rag_engine import rag_engine

load_dotenv()

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
GROQ_MODEL = os.getenv("GROQ_MODEL", "qwen/qwen3.6-27b")

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Executes on service startup to seed baseline handbook documents."""
    default_pdf_path = "/app/data/defaults/global_SOP.pdf"
    if os.path.exists(default_pdf_path):
        print("[BOOT]: Baseline corporate handbook detected. Generating embedding vectors...")
        try:
            chunks_indexed = rag_engine.process_and_index_pdf(
                file_path=default_pdf_path,
                collection_name="supply_chain_defaults",
                origin_name="global_SOP.pdf"
            )
            print(f"[BOOT]: Indexed {chunks_indexed} default SOP chunks.")
        except Exception as e:
            print(f"[BOOT ERROR]: Error while seeding default collection: {e}")
    else:
        print("[BOOT WARN]: Missing default PDF at /app/data/defaults/global_SOP.pdf. Skipping seeding.")
    yield

class EnvironmentMetadata(BaseModel):
    route_id: Optional[str] = "Unknown-Corridor"
    road_condition: Optional[str] = "Standard-Paved"
    current_weather: Optional[str] = "Clear"

class Shipment(BaseModel):
    product_name: str
    quantity: int
    source: str
    destination: str
    status: str
    userID: Optional[str] = None
    sourceID: Optional[str] = None
    metadata_env: Optional[EnvironmentMetadata] = None

class RebalanceRequest(BaseModel):
    product_name: str
    deficit_warehouse_id: int
    inventory_context: List[Dict[str, Any]]
    constant_restock_qty: int

app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def extract_and_parse_json(content: str) -> dict:
    """Strips <think> tags, markdown fences, and extracts the first valid JSON object safely using raw_decode."""
    # 1. Strip thinking tags if generated by Qwen reasoning models
    cleaned = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    if "<think>" in cleaned:
        cleaned = re.sub(r"<think>.*", "", cleaned, flags=re.DOTALL).strip()

    # 2. Strip markdown code fences
    cleaned = re.sub(r"```(?:json)?", "", cleaned).strip()

    # 3. Locate the opening JSON brace
    start = cleaned.find('{')
    if start == -1:
        raise ValueError(f"No JSON block detected in model output: {content}")

    substring = cleaned[start:]

    # 4. Attempt standard raw_decode first (ignores any trailing commentary or extra data)
    try:
        decoder = json.JSONDecoder()
        obj, _ = decoder.raw_decode(substring)
        return obj
    except Exception:
        pass

    # 5. Fallback: sanitize unescaped newlines/tabs inside string literals
    result = []
    in_string = False
    escape_next = False
    for char in substring:
        if escape_next:
            result.append(char)
            escape_next = False
        elif char == '\\':
            result.append(char)
            escape_next = True
        elif char == '"':
            result.append(char)
            in_string = not in_string
        elif in_string and char == '\n':
            result.append('\\n')
        elif in_string and char == '\r':
            result.append('\\r')
        elif in_string and char == '\t':
            result.append('\\t')
        else:
            result.append(char)

    sanitized = ''.join(result)
    decoder = json.JSONDecoder()
    obj, _ = decoder.raw_decode(sanitized)
    return obj

@app.post("/upload-kb")
async def upload_custom_user_intelligence(
    file: UploadFile = File(...),
    userID: str = Form(...)
):
    if not file.filename.endswith('.pdf'):
        raise HTTPException(status_code=400, detail="Invalid file type. Only PDFs are supported.")

    temp_dir = "/app/data/temp"
    os.makedirs(temp_dir, exist_ok=True)
    target_path = os.path.join(temp_dir, f"{uuid.uuid4().hex[:6]}_{file.filename}")

    try:
        with open(target_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        collection_target = f"user_kb_collection_{userID}"
        total_chunks = rag_engine.process_and_index_pdf(
            file_path=target_path,
            collection_name=collection_target,
            origin_name=file.filename
        )

        return {
            "status": "SUCCESS",
            "chunks": total_chunks,
            "target_silo": collection_target
        }
    except Exception as error:
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {str(error)}")
    finally:
        if os.path.exists(target_path):
            os.remove(target_path)

@app.post("/analyze")
async def analyze_shipment(shipment: Shipment):
    env = shipment.metadata_env or EnvironmentMetadata()

    search_query = f"{shipment.destination} road infrastructure condition potholes damage {shipment.product_name} transit rules"
    rag_context = rag_engine.fetch_combined_context(
        search_query=search_query,
        user_id=shipment.userID,
        top_k=5
    )

    prompt = f"""
SYSTEM: You are the Autonomous Supply Chain Guardian routing intelligence.
Respond ONLY with a single valid JSON object. Do not include thinking tokens, markdown fences, or commentary outside the JSON.

OPERATIONAL BRIEFINGS & CORRIDOR MANUALS:
{rag_context if rag_context else "Standard precautions apply."}

LIVE TELEMETRY:
- Asset: {shipment.product_name} ({shipment.quantity} units)
- Corridor: {shipment.source} -> {shipment.destination}
- Route: {env.route_id}
- Surface Condition: {env.road_condition}
- Weather: {env.current_weather}
- Pipeline Status: {shipment.status}

RULES:
1. Review Corridor Manuals. If road damage, potholes, or construction are reported along the route or at destination (e.g. Kanpur/Panki), assign "High" or "Medium" risk.
2. If asset is Hazardous (Explosives, Batteries, Chemicals, Acid), assign "High" risk.
3. In 'reasoning', cite the specific road conditions or hazards.
4. If risk is High or Medium, 'ai_action' MUST provide an actionable mitigation directive. If Low, set 'ai_action' to "No action required."

OUTPUT STRICT JSON:
{{
    "risk_level": "High" | "Medium" | "Low",
    "reasoning": "Brief explanation",
    "ai_action": "Actionable directive"
}}
"""
    try:
        response = groq_client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_completion_tokens=4096,
            top_p=0.95
        )
        content = response.choices[0].message.content or ""
        return extract_and_parse_json(content)
    except Exception as e:
        print(f"[ANALYZE ERROR]: {str(e)}")
        raise HTTPException(status_code=500, detail=f"LLM analysis execution failed: {str(e)}")

@app.post("/rebalance")
async def analyze_rebalance(data: RebalanceRequest):
    inventory_summary = json.dumps(data.inventory_context, indent=2)

    prompt = f"""
SYSTEM: Autonomous Supply Chain Guardian.
Respond ONLY with a single valid JSON object. Do not output preamble, markdown fences, or extra text.

TASK: Choose source warehouse to restock {data.product_name} by {data.constant_restock_qty} units for Deficit Hub {data.deficit_warehouse_id}.

DATA:
{inventory_summary}

RULES:
1. Source warehouse must have (Stock - {data.constant_restock_qty}) > its own threshold.
2. Select hub with largest surplus. If none qualify, status = "INSUFFICIENT".

OUTPUT STRICT JSON:
{{
    "status": "EXECUTE" | "INSUFFICIENT",
    "source_id": 1,
    "qty": {data.constant_restock_qty},
    "reasoning": "Explanation"
}}
"""
    try:
        response = groq_client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_completion_tokens=2048
        )
        content = response.choices[0].message.content or ""
        return extract_and_parse_json(content)
    except Exception as e:
        print(f"[REBALANCE ERROR]: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Rebalance execution failed: {str(e)}")